### ISSUE TITLE
Project is still alive?

### ISSUE THREAD

**Issue by pascalandy** [nimmis/docker-btsync#1]
Hi,

I just run test on my mac and my VPS and it yorks good. As I see the project hasn't been updates since 6 months, wondering if it's still active ?

The link in the Dockerfile is dead - `curl https://download-cdn.getsync.com/stable/linux-x64/BitTorrent-Sync_x64.tar.gz | tar xfz`

Thanks!
twitter.com/_pascalandy

**Comment by nimmis** [comment]
Yes, but they changed the name of the program to resilio and made it not sync compatible so I decided to leave this with the last version of btsync and make a new container with the new resilio client.

The docker container is **nimmis/resilio-sync**

**Comment by pascalandy** [comment]
Thank you very much for letting me know :-)
